package com.alibaba.android.arouter.routes;

import com.alibaba.android.arouter.facade.enums.RouteType;
import com.alibaba.android.arouter.facade.model.RouteMeta;
import com.alibaba.android.arouter.facade.template.IProviderGroup;
import com.lizejun.demo.module.store.StoreModuleServiceImpl;
import java.lang.Override;
import java.lang.String;
import java.util.Map;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER. */
public class ARouter$$Providers$$modulestore implements IProviderGroup {
  @Override
  public void loadInto(Map<String, RouteMeta> providers) {
    providers.put("com.lizejun.demo.lib.base.service.IStoreModuleService", RouteMeta.build(RouteType.PROVIDER, StoreModuleServiceImpl.class, "/store/service", "store", null, -1, -2147483648));
  }
}
