package com.alibaba.android.arouter.routes;

import com.alibaba.android.arouter.facade.enums.RouteType;
import com.alibaba.android.arouter.facade.model.RouteMeta;
import com.alibaba.android.arouter.facade.template.IRouteGroup;
import com.lizejun.demo.module.home.HomeFragment;
import com.lizejun.demo.module.home.KeeponServiceImpl;
import java.lang.Override;
import java.lang.String;
import java.util.Map;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER. */
//这个是开头的
public class ARouter$$Group$$home implements IRouteGroup {
  @Override
  public void loadInto(Map<String, RouteMeta> atlas) {
    atlas.put("/home/keepon", RouteMeta.build(RouteType.PROVIDER, KeeponServiceImpl.class, "/home/keepon", "home", null, -1, -2147483648));
    atlas.put("/home/main", RouteMeta.build(RouteType.FRAGMENT, HomeFragment.class, "/home/main", "home", null, -1, -2147483648));
  }
}
